<a href="https://colab.research.google.com/github/MatheusRitchielle/analise-de-dados/blob/main/analise_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [1]:
#Importando bibliotecas
import numpy as np

#Criação de Arrays


In [ ]:
help(np.array)

In [3]:
#criação de um array
l = [1, 2, 3]
x = np.array(l)
print('x: ', x)
print('Shape: ', x.shape)

x:  [1 2 3]
Shape:  (3,)


In [4]:
type(x)

numpy.ndarray

In [5]:
#Criação de array 2d: Listas aninhadas
l = [[1, 2], [3,4]]
x = np.array(l)
print('x:\n', x)
print('shape', x.shape)

x:
 [[1 2]
 [3 4]]
shape (2, 2)


In [8]:
type(x)

numpy.ndarray

In [9]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [7]:
#Array contendo apenas 0's
dim = (2,2) # (linhas, colunas)
x = np.zeros(dim)
print('x:\n', x)
print('shape', x.shape)

x:
 [[0. 0.]
 [0. 0.]]
shape (2, 2)


In [10]:
#Array contendo apenas 1's
size = (2, 2) # (linhas, colunas)
x = np.ones(size)
print('x:\n', x)
print('shape', x.shape)

x:
 [[1. 1.]
 [1. 1.]]
shape (2, 2)


In [11]:
#Criação de valores dentro de um intervalo
#Valores uniformes entre 5 e 15
x_min, x_max = 5,12
x = np.linspace(start=x_min, stop=x_max, num=6)
print('x:\n', x)
print('shape', x.shape)

x:
 [ 5.   6.4  7.8  9.2 10.6 12. ]
shape (6,)


In [12]:
#criação de matriz identidade
n = 4
x = np.eye(n)
print('x:\n', x)
print('shape', x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape (4, 4)


In [13]:
#Criação de valores aleatórios
#np.random.seed(10)
x = np.random.random(size=(2,3))
print('x:\n', x)
print('shape', x.shape)

x:
 [[0.99973442 0.26891791 0.16101412]
 [0.82285155 0.60297584 0.00819866]]
shape (2, 3)


#indexação de arrays
